// src/theme/themeConfig.ts
import {
    LucidePalette,
    LucideHeart,
    LucideMonitor,
    LucideSparkles,
    LucideType,
    LucideCandy,
    LucidePen,
    LucideFileText,
    LucideBook,
    LucideMusic,
    LucideMusic4,
    LucideDisc,
    LucideMusic2,
    LucideMic,
    LucideMic2,
    LucideMicVocal,
    LucideMicOff,
  } from "lucide-react";
  
  export type Theme = "tone1" | "tone2" | "tone3" | "tone4";
  
  export const themeConfig = {
    tone1: {
      panel: "bg-(--color-surface-card) text-(--color-icon)",
      button: "bg-(--color-iconbutton) text-(--color-icon) border-1 border-(--color-iconborder-border)",
      hover: "hover:bg-(--color-iconbutton-hover)",
      backgroundIcon: LucidePalette,
      textIcon: LucideType,
      stickyIcon: LucidePalette,
      audioIcon: LucideMusic,
      micIcon: LucideMic,
    },
    tone2: {
      panel: "bg-(--color-surface-card) text-(--color-icon)",
      button: "bg-(--color-iconbutton) text-(--color-icon) border-1 border-(--color-iconborder-border)",
      hover: "hover:bg-(--color-iconbutton-hover)",
      backgroundIcon: LucideHeart,
      textIcon: LucideCandy,
      stickyIcon: LucideHeart,
      audioIcon: LucideMusic4,
      micIcon: LucideMic2,
    },
    tone3: {
      panel: "bg-(--color-surface-card) text-(--color-icon)",
      button: "bg-(--color-iconbutton) text-(--color-icon) border-1 border-(--color-iconborder-border)",
      hover: "hover:bg-(--color-iconbutton-hover)",
      backgroundIcon: LucideMonitor,
      textIcon: LucideMonitor,
      stickyIcon: LucideFileText,
      audioIcon: LucideDisc,
      micIcon: LucideMicVocal,
    },
    tone4: {
      panel: "bg-(--color-surface-card) text-(--color-icon)",
      button: "bg-(--color-iconbutton) text-(--color-icon) border-1 border-(--color-iconborder-border)",
      hover: "hover:bg-(--color-iconbutton-hover)",
      backgroundIcon: LucideSparkles,
      textIcon: LucidePen,
      stickyIcon: LucideBook,
      audioIcon: LucideMusic2,
      micIcon: LucideMicOff,
    },
  } as const;